/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateCollaborationBox.java
 *
 * Created on 2011-11-24, 07:05:30
 */
package org.netbeans.zp.gui;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.jivesoftware.smack.XMPPException;
import org.netbeans.zp.client.XMPPClient;

/**
 *
 * @author Tomek
 */
public class CreateCollaborationBox extends javax.swing.JDialog implements Runnable {
    private String n;
    private ArrayList<String> r;
    /** Creates new form CreateCollaborationBox */
    public CreateCollaborationBox(java.awt.Frame parent, boolean modal, String nickname) {
        super(parent, modal);
        initComponents();
        n = nickname;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        roomNameField = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.netbeans.zp.gui.KomunikatorApp.class).getContext().getResourceMap(CreateCollaborationBox.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        roomNameField.setText(resourceMap.getString("roomNameField.text")); // NOI18N
        roomNameField.setName("roomNameField"); // NOI18N

        createBtn.setText(resourceMap.getString("createBtn.text")); // NOI18N
        createBtn.setName("createBtn"); // NOI18N
        createBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(createBtn)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(roomNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createBtn)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createBtnMouseClicked
        // TODO add your handling code here:
        if (roomNameField.getText() == ""){
            JOptionPane.showMessageDialog( this, "Wpisz nazwę pokoju");
        }
        else{
            /*if (f.size() == 1){
                if (codeAndChatBox == null){
                    try {
                        XMPPClient.getInstance().createCollaboration(roomNameField.getText(), n);
                        codeAndChatBox = new CodeAndChat(KomunikatorApp.getApplication().getMainFrame(), true, n);
                    } catch (XMPPException ex) {
                        Logger.getLogger(CreateCollaborationBox.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    codeAndChatBox.setTitle(roomNameField.getText());
                    codeAndChatBox.setLocationRelativeTo(this.getParent());
                    codeAndChatBox.setVisible(true);
                }
                else{
                    codeAndChatBox.dispose();
                    codeAndChatBox = null;
                    createBtnMouseClicked(evt);
                }
            }
            else{*/
                if (codeAndConferenceBox == null){
                    try {
                      //  XMPPClient.getInstance().createCollaboration(roomNameField.getText(), n);
                        codeAndConferenceBox = new CodeAndConference(KomunikatorApp.getApplication().getMainFrame(), true, n, roomNameField.getText(), false); 
                    } catch (XMPPException ex) {
                        Logger.getLogger(CreateCollaborationBox.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    codeAndConferenceBox.setTitle(roomNameField.getText() + "@conference.draugr.de | " + n);
                    codeAndConferenceBox.setLocationRelativeTo(this.getParent());
                    codeAndConferenceBox.setVisible(true);
                }
                else{
                    codeAndConferenceBox.dispose();
                    codeAndConferenceBox = null;
                    createBtnMouseClicked(evt);
                }
            //}
        }
    }//GEN-LAST:event_createBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField roomNameField;
    // End of variables declaration//GEN-END:variables
    
    private JDialog codeAndConferenceBox;
    private JDialog codeAndChatBox;
    
    public void run() {
        
    }
}
