/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * newUser.java
 *
 * Created on 2011-11-11, 21:47:36
 */
package org.netbeans.zp.gui;

import java.io.BufferedReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jivesoftware.smack.XMPPException;
import org.jivesoftware.smack.packet.Registration;
import org.netbeans.zp.client.RegistrationListener;
import org.netbeans.zp.client.XMPPClient;

/**
 *
 * @author Dom
 */
public class newUser extends javax.swing.JDialog implements RegistrationListener, Runnable {

  /** Creates new form newUser */
  public newUser(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    getRootPane().setDefaultButton(signInBtn);
    XMPPClient.getInstance().setRegistrationListener(this);
    XMPPClient.getInstance().getInvitationMessage();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signInBtn = new javax.swing.JButton();
        loginField = new javax.swing.JTextField();
        passwordField1 = new javax.swing.JPasswordField();
        passwordField2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.netbeans.zp.gui.KomunikatorApp.class).getContext().getResourceMap(newUser.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        signInBtn.setText(resourceMap.getString("signInBtn.text")); // NOI18N
        signInBtn.setName("signInBtn"); // NOI18N
        signInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInBtnMouseClicked(evt);
            }
        });

        loginField.setText(resourceMap.getString("loginField.text")); // NOI18N
        loginField.setName("loginField"); // NOI18N

        passwordField1.setText(resourceMap.getString("passwordField1.text")); // NOI18N
        passwordField1.setName("passwordField1"); // NOI18N

        passwordField2.setText(resourceMap.getString("passwordField2.text")); // NOI18N
        passwordField2.setName("passwordField2"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(signInBtn)
                        .addGap(167, 167, 167))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(signInBtn)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInBtnMouseClicked
      
      String login = loginField.getText();
      String pass = String.valueOf( passwordField1.getPassword() );
      
      if (/*pass == String.valueOf( passwordField2.getPassword() ) && */login != null && pass != null){
      
          attr.put("username", login);
          attr.put("password", pass);

          System.out.println("'" + login + "' haslo: '" + pass + "'");
          try {
              XMPPClient.getInstance().register(attr);
          } catch (XMPPException ex) {
              Logger.getLogger(newUser.class.getName()).log(Level.SEVERE, null, ex);
          }
          //dispose();
      } 
      else {
        System.out.println("Hasła niezgodne!");
        JOptionPane.showMessageDialog( this, "Nie wszystkie pola zostały wypełnione");
        //jButton1MouseClicked(evt);
      }
    }//GEN-LAST:event_signInBtnMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField loginField;
    private javax.swing.JPasswordField passwordField1;
    private javax.swing.JPasswordField passwordField2;
    private javax.swing.JButton signInBtn;
    // End of variables declaration//GEN-END:variables

  @Override
  public void invitation(Registration msg) {
    System.out.println("INSTR: " + msg.getInstructions() );
    attr = msg.getAttributes();
    int i = 0;
    for (String s : attr.keySet()) {
      System.out.println("Pole " + s);
    }
  }

  @Override
  public void success(Registration msg) {
    JOptionPane.showMessageDialog( this.getParent() ,"Pomyślnie zarejestrowano użytkownika");
    dispose();
  }

  @Override
  public void error(Registration msg) {
    System.out.println("Błąd " + msg.getError().getCode() + " type: " + msg.getError().getType().toString() + "msg: " + msg.getError().getMessage());
    JOptionPane.showMessageDialog( this ,"Rejestracja nie powiodła się.");
    XMPPClient.getInstance().getInvitationMessage();
  }

  @Override
  public void run() {
  }
  
  private Map<String, String> attr = null;
  private boolean isEqual = false;
  String s1 = null, s2 = null, v1 = null, v2 = null;
}
